default_language_version:
  python: python3
exclude: ^(tests/testfiles/)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: debug-statements
    language_version: python3
