rejected_smiles=[
'C=C/C=C\[C@@H]1C[C@@]21NCC2',
'C=C/C=C\[C@H]1C[C@@H]1C#N',
'C=C/C=C\[C@@H]1CC1=C',
'C=C/C=C\[C@H]1C[C@@H]1C[C@@H](C)O',
'C=C/C=C\C1CC1',
'C=C/C=C\[C@H]1CN1C=C/C=C\C=C/C',
'C=C/C=C\[C@@H]1C[C@@H]1C#C',
'C=C/C=C\[C@H]1C[C@@H]1C=O',
'C=C/C=C\[C@@H]1C[C@H]1C=O',
'C=CC[C@H]1[C@H]2C[C@H]2[C@@H]1O',
'C=C/C=C\[C@H]1C[C@@H]1/C(=N\O)/C',
'C=C/C=C\[C@H]1C[C@@H]1C(=O)C',
'C=C/C=C\[C@@H]1C[C@H]1[C@H](O)C',
'C=C/C=C\[C@H]1CC1=O',
'C=C/C=C\[C@@H]1C[C@H]1[C@@H](O)C',
'C(=C/C=C\[C@@H]([NH2][CH2])C)=C',
'C=C/C=C\[C@H]1CN1',
'C=C/C=C\[C@H]1C[C@@H]1[C@@H](O)C#C',
'C=C/C=C\[C@H]1C[C@@H]1O',
'C=C/C=C\[C@H]1CO1',
'C=CC(/C=C/C=C)C=C',
'C=C/C=C\[C@H]1C[C@@H]1CC',
'C(#C)/C=C\CCO',
'C=C/C=C\C=C(C)C',
'C=C/C=C\[C@@H]1C[C@H]1[C@@H](O)CC',
'C=CC[C@@H]([C@@H]1[C@@H]2C[C@H]12)C',
'C(#C)/C=C\/CCO',
'C=C/C=C\[C@@H]1C[C@H]1NC',
'C=C/C=C\/[C@H]1C[C@@H]1[C@@H](O)C#C',
'C(=C)/C=C\C=C1CCC1',
'C=CC/C(=C/C=C)/CC',
'C=C/C=C\C=C/C',
'C(=C/C=C\C=C/N)=CC#C',
'C=C/C=C\[C@H]1C[C@H]1O',
'C=C/C=C\C=C\C',
'C=C/C=C\[C@@H]1C[C@@H]1OC',
'C=C/C=C\[C@@H]1C[C@]21NCC2',
'C=C/C=C\[C@H]1C[C@H]1C#N',
] 


accepted_smiles = [
'C=CC[C@@H]1[C@@H]2C[C@@H]2[C@@H]1O',
'C=C[C@@H]1[C@@H]2C=CCC[C@H]12',
'C1C=CC[C@@]2(C=CC2=C1)C',
'C\/1(=C/O)/CC=CC=C1',
'C1C=C[C@H](C=C1)CC#CC',
'[C@H]12C[C]2[CH]C[C@@H]2[C@H]1[C@@H]2O',
'[C@@H]12C[C]2[CH]C[C@H]2[C@@H]1[C@H]2O',
'C(=C/O)/CC=CC=C1',
'[C]1[CH][C]2[C@H]3[C@@H](C1)[C@H]3[C@@H]2CC',
'C1[CH]C=C[C@H]2C[N@@]31[C@@H]2[C@@H]3C',
'C1C=CC[C@](C=C)(C)C1',
'[C]1[CH]C=C[C@@H]2[C@H]1[NH]2CCC',
'C1=CC=C[C@@H]2[C@H]1[C@H]2CC',
'C1CC=C[C@@H]2[C@H]1[C@H]2CCC|1(|CO)CC=CC=C|1',
'C1C=CC[C@H](C=C)C1',
'C1[C@@H]2[C@@H]3C=C[C@@]1(C)C[C@H]23',
'C1/C(=C/C=C)/C=CC=C1',
'C1[C@H](C=CC=C1)OC',
'C1C=CC=CN(C1)CC',
'C1(=C)C=C[C@@H]2[C@@H]3[C@@H]([C@H]23)O1',
'[C]1[CH]C=CC=C[NH]1CC',
'C=CC[C@@H]1[C@@H]2C[C@@H]2C1',
'C1CCC=C(C=C)C1',
'C1CC=C[C@@H]2[C@H]1[C@H]2CC',
'[CH]1[C@@H]2[C@H](C=C[C@H]([CH]1)CN)C2',
'C1CC=C[C@H]2[C@@H]1[C@@H]2CC',
'C1C=CC=C[C@H](C1)[C@@H]1NC1',
'C1C=CC[C@](C=C)(C1)C',
'C[C@@H]1CC=C[C@H]2[C@@H]1C2',
'[C]1[CH]C=C[C@H]([C@H]([CH]1)C)C',
'C1C=CC=C[C@@H]1OC=C',
'C1[C@H]2[C@H]3C=C[C@]1(C)N[C@@H]23',
'C1CC=C[C@@H]2[C@H]1[C@H]2[C@H](C#N)N',
]

aromatic_ring_smiles = [
'c1(ccccc1)', 'c1ccccc1', 'c1ccc(cc1)', 'c1(c(cccc1)',
'c1c(cccc1)',
'c12c(cccc1)',
'C1=CC=CC=C1',
'C1=CC(=CC=C1)',
'C1(=CC=CC=C1)',
'C1(=CC=CCC1)C',
'C1(=CC=CC=[C]1)',
'C1(=[C]C=CC=C1)',
'C1(=C[C]=CC=C1)',
'C1C([H])C=CC=C1',
'[C]1=CC=CC=C1',
'[C]1=C(C=CC=C1)',
'[C]1=CC=C[CH][C@@H]1',
'C1:C:C:C:C:C1',
'C1C=CC=C(C1)',
'C1C=CC=C[C@H](C1)' ]


#check below for clarification
maybe_smiles = [
'C12[C@@H](C=CC=C1)C2',
'C12=C[CH]C=C[C@H]1',
'C1C=CC=C[C@H]1',
'[C]1C=CC=CCCO1',
'C=CC[C@H]1[C@H]2C[C@H]2C1',
'C1[C@H]2[CH][CH][C@H]3C[C@@]12[C@@H]3C',
'[C@H]12[C](C=CC=C1)[C]([C@@H](C)O)N2',
'C1[C@H]2C=C[C@@H]2CC=CC1=C',
'[C]1[CH]C=C[C@]2([CH]1)[C@H]([C@H]2N)C',
]	
